name: Java CI

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        run:  ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body:  "Please download the jar specific to your platform.
          Or, if you're not sure which jar to use, then use the `-all.jar` file."
          files: |
                 build/libs/BiomeTool-*-all.jar
                 build/libs/BiomeTool-*-win.jar
                 build/libs/BiomeTool-*-osx.jar
                 build/libs/BiomeTool-*-linux.jar